export const whoAmIInfoPanel = {
    id: 'who',
    darkPanel: false,
    headline: "Who Am I",
    description1: "My name is Dylan and I am currently in my second year studying Computer Science at Queens' College, University of Cambridge",
    description2: "My passion comes from learning new things, from technology to sports I always enjoy pushing myself outside of my comfort zone to try out new things",
    description3: "I love organising and leading events, I am the leader of 2 Cambridge clubs and have helped organise events in both the Hex Cambridge hackathon and the Cambridge vs Oxford eSports varsity",
    button: false,
    buttonLabel: "",
    imgStart: false, 
    img: require('../../imgs/Selection_009.png').default, // 17/14/9
    internal: true,
    link: "/",
    circleImg: true,
    alt: "Img desc",
    primary:  true,
    arrow: true,
};

export const compSciInterestsInfoPanel = {
    id: 'compsci',
    darkPanel: true,
    headline: "Computer Science Interests",
    description1: "My favourite languages are Python, Java, JavaScript and C++",
    description2: "I am also really interested in AI and how it can be used to improve our lives in many new ways",
    description3: "Building new programs is one of my favourite hobbies as it always lets me explore new topics in the world of computer science that may not be covered at university",
    button: false,
    buttonLabel: "Visit Github",
    imgStart: true,
    img: require('../../imgs/code3.jpg').default,
    internal: true,
    link: "/",
    circleImg: true,
    alt: "Img desc",
    primary:  true,
    arrow: true,
};

export const outsideOfCompSciInfoPanel = {
    id: 'noncompsci',
    darkPanel: false,
    headline: "Outside of Computer Science",
    description1: "I love the Scouting community and have been a Scout for over 10 years, and gone on to become a Scouting Young Leader for a further 4 years",
    description2: "When I want to relax, reading books is my go-to - my favourite genre is fantasy and I can get lost in a good book for hours",
    description3: "I also enjoy playing sports, and some sports I have played in the past are: judo, badminton, golf and cricket",
    button: false,
    buttonLabel: "Visit Github",
    imgStart: false,
    img: require('../../imgs/scouts4.png').default,
    internal: true,
    link: "/",
    circleImg: true,
    alt: "Img desc",
    primary:  true,
    arrow: true,
};