export const whoAmIInfoPanel = {
    id: 'who',
    darkPanel: false,
    headline: "Who Am I",
    description1: "My name is Dylan and I am currently in my second year studying Computer Science at Queens' College, University of Cambridge",
    description2: "My passion comes from learning new things - from technology to sports I always enjoy pushing myself outside of my comfort zone to try out something new",
    description3: "I love organising and leading events, I am the leader of 2 Cambridge clubs and have helped organise events in both the Hex Cambridge hackathon and the Cambridge vs Oxford eSports varsity",
    button: false,
    buttonLabel: "",
    imgStart: false, 
    img: require('../../imgs/Selection_009.png').default, // 17/14/9
    internal: true,
    link: "/",
    circleImg: true,
    alt: "Img desc",
    primary:  true,
    arrow: true,
};

export const compSciInterestsInfoPanel = {
    id: 'compsci',
    darkPanel: true,
    headline: "Computer Science Interests",
    description1: "I enjoy learning new languages as they teach me new ways of thinking and how to go about solving different types of problems",
    description2: "I am also really interested in AI and Machine Learning - especially how it can be used to improve our lives in exciting new ways",
    description3: "Building programs is one of my favourite hobbies as it lets me explore new topics in the world of computer science that may not be covered at university",
    button: false,
    buttonLabel: "Visit Github",
    imgStart: true,
    img: require('../../imgs/code3.jpg').default,
    internal: true,
    link: "/",
    circleImg: true,
    alt: "Img desc",
    primary:  true,
    arrow: true,
};

export const outsideOfCompSciInfoPanel = {
    id: 'noncompsci',
    darkPanel: false,
    headline: "Outside of Computer Science",
    description1: "I love being part of the Scouting community and have been a Scout for over 10 years. I then went on to become a Scouting Young Leader for a further 4 years",
    description2: "When I want to relax, I enjoy reading books - my favourite genre is fantasy and I can get lost in a good book for hours",
    description3: "I also like playing sports, some sports I have played in the past are: Judo, badminton, golf and cricket - and I hope to try even more in the future!",
    button: false,
    buttonLabel: "Visit Github",
    imgStart: false,
    img: require('../../imgs/scouts4.png').default,
    internal: true,
    link: "/",
    circleImg: true,
    alt: "Img desc",
    primary:  true,
    arrow: true,
};