export const garyInfoPanel = {
    id: 'about',
    darkPanel: false,
    topLine: "Python & C++",
    headline: "Project Gary",
    description1: "I am a co-founder of Project Gary, an organisation with the aim to try and build the world's most advanced biomimetric robot",
    description2: "Currently creating prototypes for the arm which match the dexterity of a human arm",
    description3: "Project funded by the University of Cambridge",
    button: true,
    buttonLabel: "Visit Github",
    imgStart: false, 
    img: require('../../imgs/Gary.svg').default,
    internal: false,
    link: "https://github.com/Team-Gary/Gary-the-Robot-ROS",
    circleImg: false,
    alt: "Img desc",
    primary:  true,
    arrow: true,
};

export const rubiksInfoPanel = {
    id: 'about',
    darkPanel: true,
    topLine: "Java & OpenGL",
    headline: "Rubik's Cube Solver",
    description1: "Takes a video of a strambled Rubik's cube as an input and converts this into a 3D cube model which is rendered using OpenGL",
    description2: "Figures out how to solve the cube and shows the solving steps on the 3D render of the cube",
    button: true,
    buttonLabel: "Visit Github",
    imgStart: true, 
    img: require('../../imgs/Rubiks.png').default,
    internal: false,
    link: "https://github.com/DylanMoss1/RubiksCubeSolver",
    circleImg: false,
    alt: "Img desc",
    primary:  true,
    arrow: true,
};

export const portfolioInfoPanel = {
    id: 'about',
    darkPanel: false,
    topLine: "JavaScript: MERN Stack",
    headline: "Personal Portfolio Website",
    description1: "A website I built using the MERN stack and deployed on the cloud using Docker containers",
    description2: "Includes database integration to store 'contact me' requests and automatic email replies",
    button: true,
    buttonLabel: "Visit Github",
    imgStart: false, 
    img: require('../../imgs/Portfolio.png').default,
    internal: false,
    link: "https://github.com/DylanMoss1/Personal-Website",
    circleImg: false,
    alt: "Img desc",
    primary:  true,
    arrow: true,
};

export const ganttInfoPanel = {
    id: 'about',
    darkPanel: true,
    topLine: "JavaScript: React & Firebase",
    headline: "Gantt Chart Creator",
    description1: "Currently developing a website which allows you to create Gantt Charts, includes multi-level sub-tasks and dependency management",
    description2: "Using Firebase backend for cloud storage, authentication and cloud functions",
    button: true,
    buttonLabel: "Github Coming Soon",
    imgStart: true, 
    img: require('../../imgs/Gantt2.png').default,
    internal: true,
    link: "/projects",
    circleImg: false,
    alt: "Img desc",
    primary:  true,
    arrow: false,
};

export const otherInfoPanel = {
    id: 'about',
    darkPanel: false,
    topLine: "Python / JavaScript",
    headline: "Other Projects",
    description1: "A variety of other projects including computer vision, websites and hackathon projects",
    description2: "Visit my github page to find out more",
    button: true,
    buttonLabel: "Visit Github",
    imgStart: false, 
    img: require('../../imgs/Other2.png').default,
    internal: false,
    link: "https://github.com/DylanMoss1?tab=repositories",
    circleImg: false,
    alt: "Img desc",
    primary:  true,
    arrow: true,
};