export const garyInfoPanel = {
    id: 'gary',
    darkPanel: false,
    topLine: "Python & C++",
    headline: "Wyropa",
    description1: "I am a co-founder of Wyropa; a small, dedicated team funded by the University of Cambridge with the aim to try and build the world's most advanced biomimetic robot",
    description2: "We have been working hard this summer to try and build a prototype for the robot's arm, trying to match the dexterity of a real human's arm",
    description3: "",
    button: true,
    buttonLabel: "Visit Github",
    imgStart: false, 
    img: require('../../imgs/Gary.svg').default,
    internal: false,
    link: "https://github.com/Wyropa/Project-Gary",
    circleImg: false,
    alt: "Img desc",
    primary:  true,
    arrow: true,
};

export const rubiksInfoPanel = {
    id: 'rubiks',
    darkPanel: true,
    topLine: "Java & OpenGL",
    headline: "Rubik's Cube Solver",
    description1: "A project I undertook that I've wanted to try for years, creating a program that can solve a Rubik's cube!",
    description2: "Using OpenCV for video input and OpenGL for rendering, I can take a video input of a scrambled cube and show the solution on a rendered simulation of the cube",
    button: true,
    buttonLabel: "Visit Github",
    imgStart: true, 
    img: require('../../imgs/Rubiks.png').default,
    internal: false,
    link: "https://github.com/DylanMoss1/RubiksCubeSolver",
    circleImg: false,
    alt: "Img desc",
    primary:  true,
    arrow: true,
};

export const portfolioInfoPanel = {
    id: 'portfolio',
    darkPanel: false,
    topLine: "JavaScript: MERN Stack",
    headline: "Personal Portfolio Website",
    description1: "A website I made to give an insight into who I am as a person and some of the projects I've been working on",
    description2: "A full stack website (using the MERN stack) that is automatically built and deployed on the cloud using Docker containers",
    button: true,
    buttonLabel: "Visit Github",
    imgStart: false, 
    img: require('../../imgs/Portfolio.png').default,
    internal: false,
    link: "https://github.com/DylanMoss1/Personal-Website",
    circleImg: false,
    alt: "Img desc",
    primary:  true,
    arrow: true,
};

export const ganttInfoPanel = {
    id: 'gantt',
    darkPanel: true,
    topLine: "JavaScript: React & Firebase",
    headline: "Gantt Chart Creator",
    description1: "To get more experience with cloud deployment, I'm currently in the process of making a new website to try out some of the cool features that Firebase has to offer",
    description2: "I want to make a Gantt Chart Creator to learn new skills such as how to use cloud storage, authentication and cloud functions",
    button: true,
    buttonLabel: "Github Coming Soon",
    imgStart: true, 
    img: require('../../imgs/Gantt2.png').default,
    internal: true,
    link: "/projects",
    circleImg: false,
    alt: "Img desc",
    primary:  true,
    arrow: false,
};

export const otherInfoPanel = {
    id: 'other',
    darkPanel: false,
    topLine: "Python / JavaScript",
    headline: "Other Projects",
    description1: "A variety of other fun projects including computer vision, websites and hackathon projects",
    description2: "Visit my github page to find out more",
    button: true,
    buttonLabel: "Visit Github",
    imgStart: false, 
    img: require('../../imgs/Other2.png').default,
    internal: false,
    link: "https://github.com/DylanMoss1?tab=repositories",
    circleImg: false,
    alt: "Img desc",
    primary:  true,
    arrow: true,
};
